name: Deploy Blog to GitHub Pages

on:
  push:
    branches:
      - dev  # 只在 main 分支有提交时触发部署（可以根据需要修改）

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'  # 可以根据需要修改 Node.js 版本

      # 安装依赖
      - name: Install dependencies
        run: |
          npm install
      #安装 Hexo
      - name: Install Hexo-cli 
        run: |
          npm install -g hexo-cli --save
          echo "install hexo successful"
      # 编译创建静态博客文件
      - name: Build Blog 
        run: |
          hexo clean
          hexo g
          echo "build blog successful"

      - name: Deploy Blog
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: blog-pages                 # 部署目标分支
          folder: public      # 构建后的输出目录